version: "3.8"
services:

  web:
    image: agp94/demo_docker:latest
    build: ../build
    ports:
      - "9090:80"
    networks:
      - demo-network

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis-data:/bitnami'
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      demo-network:
        aliases:
          - redis
  redis-replica:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    deploy:
      placement:
        constraints: [node.role == worker]
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - demo-network


volumes:
  demo-data:
  redis-data:
  portainer:

networks:
  demo-network: